- FakeXrmEasy.Tests/FakeContextTests/FakeContextTestPlugins.cs
- FakeXrmEasy.Tests/FakeContextTests/FakeContextTests.cs
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
- FakeXrmEasy.Tests/PluginsForTesting/ConfigurationPlugin.cs
- FakeXrmEasy.Tests/PluginsForTesting/TestContextPlugin.cs
- FakeXrmEasy/IXrmFakedContext.cs
- FakeXrmEasy/XrmFakedContext.Plugins.cs
- FakeXrmEasy/XrmFakedContext.cs
Hey Jordi,
I implemented the method for executing a plugin with configuration parameters.
Kind Regards,
DigitalFlow
> Added method that allows to execute plugin with configuration parameters

- FakeXrmEasy.2013/FakeXrmEasy.2013.csproj
- FakeXrmEasy.2015/FakeXrmEasy.2015.csproj
- FakeXrmEasy.2016/FakeXrmEasy.2016.csproj
- FakeXrmEasy.Tests.2013/FakeXrmEasy.Tests.2013.csproj
- FakeXrmEasy.Tests.2015/FakeXrmEasy.Tests.2015.csproj
- FakeXrmEasy.Tests.2016/FakeXrmEasy.Tests.2016.csproj
- FakeXrmEasy.Tests.2016/RetrieveMultiple/QueryLinkEntityTests.cs
- FakeXrmEasy.Tests/FakeContextTests/RetrieveAttributeRequestTests/RetrieveAttributeRequestTests.cs
- FakeXrmEasy.Tests/FakeContextTests/RetrieveMultiple/QueryLinkEntityTests.cs
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
- FakeXrmEasy/FakeMessageExecutors/AssociateRequestExecutor.cs
- FakeXrmEasy/FakeMessageExecutors/DisassociateRequestExecutor.cs
- FakeXrmEasy/FakeXrmEasy.csproj
- FakeXrmEasy/XrmFakedContext.Crud.cs
- FakeXrmEasy/XrmFakedContext.Queries.cs
- FakeXrmEasy/XrmFakedContext.cs
- FakeXrmEasy/XrmFakedRelationship.cs
- packages/repositories.config
I added an implementation for the associate and for the disassociate message.
There are also some tests included.
There might be some rough edges to it, but its working good so far and the tests are passing.
Kind Regards
> Added implementation for associate / disassociate message and tests

- FakeXrmEasy.Shared/FakeMessageExecutors/AssignRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestExecute.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Hey Jordi,
added implementation for assign request.
Could you push a new NuGet package soon?
Kind Regards,
Florian
> Implemented Assign Request

- FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteTransactionExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/XrmFakedContext.cs
Added a quick implementation for `ExecuteTransactionRequest`
> Added implementation for ExecuteTransactionRequest

- FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteMultipleRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/ExecuteMultipleRequestTests/ExecuteMultipleRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Hey Jordi,
I added a FakeMessageExecutor for ExecuteMultiple requests.
Kind Regards,
Florian
> Added executor for execute multiple

- FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteMultipleRequestExecutor.cs
Hey Jordi,
added quick check to execute multiple executor, just in case someone tries to execute it without requests...
Kind Regards,
Florian
> Added check for execute multiple executor

- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestUpdate.cs
Hey all,
this is a PR for #90.
Kind Regards,
Florian
> Added test for proving bug

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveTests/RetrieveRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Hey Jordi,
this PR includes a test for reproducing the issue discovered in #93.
Kind Regards,
Florian
> Added test for reproducing error when cloning entity with EntityCollections

- FakeXrmEasy.Shared/XrmRealContext.cs
- FakeXrmEasy.Tests.Shared/XrmRealContextTests/XrmRealContextTests.cs
Made a property for the connectionstring that will be used for the XrmRealContext, this to make testing on different CRM organizations easier. Also added two constructors to construct with a specific connectionstring or an already initialized organizationservice.
> Made a property for the connectionstring

- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/QueryLinkEntityTests.cs
Reproduction unit test for #128.
> Added unit test for reproduction

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveOptionSetRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveOptionSetRequestTests/RetrieveOptionSetRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Adding the RetrieveOptionSetRequestExecutor to handle RetrieveOptionsetRequests!  Also with tests.
> RetrieveOptionSetRequest implementation.

- FakeXrmEasy.Shared/FakeMessageExecutors/AddListMembersListRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeContextTests/AddListMembersListRequestTests/Tests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
The existing AddMemberListRequestExecutor was used as a template.
> Added AddListMembersListRequestExecutor plus tests.

- FakeXrmEasy.sln
Also removed the project "DevToolkitSamples" from the solution
> Edited solution file to use VS 2015 version 14.0

- FakeXrmEasy.Shared/FakeMessageExecutors/PickFromQueueRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeContextTests/AddToQueueRequestTests/AddToQueueRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/PickFromQueueRequestTests/PickFromQueueRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Fixed AddToQueueRequest - the executor was implemented, but because it was not added to the project file, it was not actually working. 
Added implementation for PickFromQueueRequest + tests
> Fixed AddToQueueRequest + added PickFromQueueRequest

- FakeXrmEasy.Shared/XrmFakedContext.CodeActivities.cs
- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Issues/Issue180.cs
Fix for Issue #180
Code now iterates through array values.
- Fix "In" condition on EntityReference
- Remove warning about unused var during build
> Fix for Issue #180

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveMultipleRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/Metadata/DateTimeAttributeBehavior.cs
- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Shared/XrmFakedContext.DateTime.cs
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/DateTimeBehaviourTests/DateTimeBehaviourTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
As there is no metadata store (yet) I added the Date & Time Field behavior to a collection.
By default the fields are set as [documented](https://technet.microsoft.com/en-us/library/dn946904.aspx).
> Added DateTime behavior

- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
> Use relationships as a source for valid attributes

- FakeXrmEasy.Shared/FakeMessageExecutors/InitializeFromRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/InitializeFromRequestTests/InitializeFromRequestTests.cs
> InitializeFrom executer no longer populates Id

- FakeXrmEasy.Shared/Services/EntityInitializer/DefaultEntityInitializerService.cs
- FakeXrmEasy.Shared/Services/IEntityInitializerService.cs
- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- Only initialize primary key property on M2M entities
Fixes #212
> Fix issue with Many to Many relationship entities

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
> When nesting linked entities use the entity logical name, not the alias, for testing metadata

- FakeXrmEasy.Shared/Enums/ProcessingStepImageType.cs
- FakeXrmEasy.Shared/Enums/ProcessingStepMode.cs
- FakeXrmEasy.Shared/Enums/ProcessingStepStage.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Shared/XrmFakedContext.Pipeline.cs
- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Pipeline/PipelineTests.cs
- FakeXrmEasy.Tests.Shared/PluginsForTesting/CreateAccountPlugin.cs
- FakeXrmEasy.Tests.Shared/PluginsForTesting/ValidatePipelinePlugin.cs
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
This is a first attempt to make it possible to register other plugins in a unittest that respond to actions under test. _This is in no way a complete reproduction of the actual CRM execution pipeline._
A common scenario is that you have plugins that provide extra fields that are needed for the execution of the plugin you want to test.
This is an example of what is possible now:
public void When_AccountNumberPluginIsRegisteredAsPluginStep_And_OtherPluginCreatesAnAccount_Expect_AccountNumberIsSet()
{
var context = new XrmFakedContext();
// Adds an accountnumber to an Account entity
context.RegisterPluginStep<AccountNumberPlugin>("Create", ProcessingStepStage.Preoperation);
// Only creates a new, empty Account entity
context.ExecutePluginWith<CreateAccountPlugin>();
var account = …
> Register processing steps for plugins

- FakeXrmEasy.Shared/FakeMessageExecutors/LoseOpportunityRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/QualifyLeadRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/WinOpportunityRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeContextTests/LoseOpportunityTests/LoseOpportunityTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/QualifyLeadTests/QualifyLeadTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/WinOpportunityRequestTests/WinOpportunityTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Hi @jordimontana82 
I added WinOpportunityRequestExecutor. It should work fine. 
Also I added few comments in code to give better undrstanding why I made something in the way I made it :)
P.S.
I was based on what You said in [this issue](https://github.com/jordimontana82/fake-xrm-easy/issues/192).
> Added WinOpportunityRequestExecutor, LoseOpportunityRequestExecutor, QualifyLeadRequestExecutor and Tests.

- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/Services/EntityInitializer/DefaultEntityInitializerService.cs
- FakeXrmEasy.Shared/Services/EntityInitializer/InvoiceDetailInitializerService.cs
- FakeXrmEasy.Shared/Services/EntityInitializer/InvoiceInitializerService.cs
- FakeXrmEasy.Shared/Services/IEntityInitializerService.cs
- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Services/EntityInitializer/InvoiceDetailInitializerServiceTests.cs
- FakeXrmEasy.Tests.Shared/Services/EntityInitializer/InvoiceInitializerServiceTests.cs
Hi Jordi,
I finally came back to this. Please review the changes and let me know if anything needs to be changed.
Most probably, you will want to change the following in `DefaultEntityInitializerService.cs`:
```c#
Dictionary<string, IEntityInitializerService> initializerServiceDictionary;
public DefaultEntityInitializerService()
{
initializerServiceDictionary = new Dictionary<string, IEntityInitializerService>()
{
{ InvoiceDetailInitializerService.EntityLogicalName, new InvoiceDetailInitializerService() },
{ InvoiceInitializerService.EntityLogicalName, new InvoiceInitializerService() }
};
}
public Entity Initialize(Entity e, Guid gCallerId, XrmFakedContext ctx, bool isManyToManyRelationshipEntity = false)
{
//
//... other code
//
if (!string.IsNullOrEmpty(e.LogicalName) && …
```
> Simple OOTB CRM functionality emulation for invoice and invoicedetail

- FakeXrmEasy.Shared/FakeMessageExecutors/CustomExecutors/NavigateToNextEntityOrganizationRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeContextTests/CustomRequestTests/NavigateToNextEntityRequestTests/NavigateToNextEntityRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Hi @jordimontana82 
While testing the code I found out that some of the CRM requests are not officially described on MSDN.
I added one custom OrganizationRequest and few links which describes what it does.
In short, it should move the given entity to next stage in given process and after moving it should set ProcessId, StageId and TraversedPath.
I do would like to hear Your opinion :)
> Added Custom OrganizationRequest which is not accessible through the SDK.

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- If we remove time from values, we should also remove time from the comparison date
- Make OnOrBefore and OnOrAfter also work
> Make On, OnOrBefore and OnOrAfter work better

- FakeXrmEasy.Shared/FakeMessageExecutors/InitializeFromRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/InitializeFromRequestTests/InitializeFromRequestTests.cs
Fix for issue #249 with two new Unit tests
> Fix for issue #249

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
- FakeXrmEasy.Tests.Shared/Extensions/EntityExtensionsTests.cs
Added support for entity lists and byte arrays to the clone attribute function to enable partylists and entity images, to fix issue #259
> Fix for issue #259

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
...when queriing with condition on Ids with dynamics crm <= 2015
> #180 -> fixes InvalidCastException 

- FakeXrmEasy.Shared/FakeMessageExecutors/ModifyAccessRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/Permissions/AccessRightsRepository.cs
- FakeXrmEasy.Shared/Permissions/IAccessRightsRepository.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/ModifyAccessRightsTests/ModifyAccessRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Added support for ModifyAccessRequest messages
> Added ModifyAccessRequest Executer

- FakeXrmEasy.Shared/Extensions/TypeExtensions.cs
- FakeXrmEasy.Shared/IXrmFakedContext.cs
- FakeXrmEasy.Shared/XrmFakedContext.CodeActivities.cs
- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Shared/XrmFakedContext.cs
Added more Execute* methods
Added defaults to some Execute* methods
Removed some redundant code
Refactored some code for readability
> Added more Execute* methods

- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestUpdate.cs
Removes incorrect handling of modifying inactive records.
> Removed incorrect update checks

- FakeXrmEasy.Shared/FakeMessageExecutors/AddUserToRecordTeamRequest.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
Added message to add user to team (access team for example)
> Add user to record team request

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveMultipleRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/RetrieveMultipleTests.cs
Adds distinct functionality to RetriveMultiple.
> Added distinct functionality

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveMultipleRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/RetrieveMultipleTests.cs
Fixes an issue where the first value of the second page was the last value of the first.
> Fixed an off by one error in the paging functionality

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveRelationshipRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Issues/Issue178.cs
In order to support .LoadProperty there wer 2 main things that were needed.  
1) needed to create RetrieveRelationshipRequestExecutor 
2) had to update the RetreiveRequestExecutor to support ManyToOne relationships  
(sorry I ddind't do this on a branch, I thought it was going to be a quick fix)
> Fix to Issue 178 (support for .LoadProperty)

- FakeXrmEasy.Shared/Extensions/XmlExtensionsForFetchXml.cs
- FakeXrmEasy.Shared/XrmFakedContext.CodeActivities.cs
- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/QueryTests/BusinessIdTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Hi Jordi - pull request created (bit slow I am afraid - my first pull request).
> EqualBusinessId - implementation and unit tests added.

- FakeXrmEasy.Shared/FakeMessageExecutors/AddMembersTeamRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/RemoveMembersTeamRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeContextTests/AddMembersTeamRequestTests/Tests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RemoveMembersTeamRequestTests/Tests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
Added Add and RemoveMembersTeamRequest
> Addremovemembersteamrequest

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
This additional check is required for the same reasons the original change was made as a fix for Issue #147.
> Additional fix for Issue #147

- FakeXrmEasy.Shared/IXrmFakedContext.cs
- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Issues/Issue308.cs
- FakeXrmEasy.Tests.Shared/PluginsForTesting/ServiceEndpointNotificationPlugin.cs
- FakeXrmEasy/Properties/AssemblyInfo.cs
> Expose IServiceEndpointNotificationService for tests

- FakeXrmEasy.Shared/FakeMessageExecutors/AssignRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/AssignRequestTests/AssignRequestTests.cs
This seemed to be missing from AssignRequest, thus, I've added it, with tests :) Based on the comments here: http://techboa.blogspot.com.es/2014/03/mscrm-what-is-difference-between-owner.html
> In AssignRequest, set OwningUser or OwningTeam as appropriate

- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Pipeline/PipelineTests.cs
- FakeXrmEasy.Tests.Shared/PluginsForTesting/PostOperationUpdatePlugin.cs
> Fix for issue #326 

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveMultipleRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Issues/Issue328.cs
- Added test for #328
- Removed distinction on ID
> Fix ID's making distinct not work

- FakeXrmEasy.9/FakeXrmEasy.9.csproj
- FakeXrmEasy.9/app.config
- FakeXrmEasy.9/packages.config
- FakeXrmEasy.Tests.9/FakeXrmEasy.Tests.9.csproj
- FakeXrmEasy.Tests.9/packages.config
> Update CRM 9 packages to latest version

- FakeXrmEasy.Shared/FakeMessageExecutors/QualifyLeadRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/QualifyLeadTests/QualifyLeadTests.cs
Implemented the solution suggested by @jordimontana82 
Closes #352
> QualifyLeadRequest should update statuscode to Qualified, instead of Open

- FakeXrmEasy.Shared/FakeMessageExecutors/BulkDeleteRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
> Add BulkDeleteRequestExecutor

- FakeXrmEasy.Shared/XrmFakedContext.Aggregations.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/AggregateTests.cs
Hello Jordi,
this PR solves #392 .
Best regards,
Betim.
> Aggregates are calculated correctly even with AliasedValue-s

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveExchangeRateRequest.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
Hello @jordimontana82 ,I've added implementation for RetrieveExchangeRateRequest.
> Added executor for RetrieveExchangeRateRequest

- FakeXrmEasy.Shared/XrmFakedContext.Aggregations.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/AggregateTests.cs
Changed via github UI - just testing if CI will run on the PR :)
> Add support for Min / Max with DateTimes

- FakeXrmEasy.Shared/FakeMessageExecutors/AssociateRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/XrmFakedRelationshipTests.cs
this PR fixes #418.
I slightly modified the proposed test cases as there were some inconsistencies with CRM behavior.
Best regards,
Betim.
P.S. Good luck for tomorrow.
> Fixed Self-Referential Many to Many relationships

- FakeXrmEasy.Shared/Extensions/XmlExtensionsForFetchXml.cs
- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/FakeContextTestFetchXmlTranslation.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/RetrieveMultipleTests.cs
this PR fixes #405,
Best regards,
Betim.
> Translation from FetchXML to QueryExpression for distinct property

- FakeXrmEasy.Shared/FakeMessageExecutors/FetchXmlToQueryExpressionRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXmlToQueryExpressionRequestTests/FetchXmlToQueryExpressionRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
Hi Jordi,
I've added support for FetchXmlToQueryExpressionRequest SDK message. Could you please review and complete the pull request.
> Added support for FetchXmlToQueryExpressionRequest

- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
> Populate PrimaryEntityId from faked plugin execution context

- FakeXrmEasy.Shared/XrmFakedContext.CodeActivities.cs
Fixes issue #473 
Affects CodeActivitys that use service endpoints.
> Add Extention for the EndPoint notification service.
