- FakeXrmEasy.Tests/FakeContextTests/LinqTests/FakeContextTestLinqQueries.cs
- FakeXrmEasy.Tests/FakeContextTests/LinqTests/MetadataInferenceTests.cs
- FakeXrmEasy.Tests/FakeContextTests/TranslateQueryExpressionTests/ConditionExpressionTests.cs
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
- FakeXrmEasy/Extensions/EntityExtensions.cs
- FakeXrmEasy/OrganizationFaults/OrganizationServiceFaultQueryBuilderNoAttribute.cs
- FakeXrmEasy/XrmFakedContext.Crud.cs
- FakeXrmEasy/XrmFakedContext.Queries.cs
> Several fixes / improvements

- FakeXrmEasy.Tests/FakeContextTests/FakeContextTests.cs
- FakeXrmEasy/XrmFakedContext.Crud.cs
Hey Jordi,
I found that the update function is not updating the modifiedOn and modifiedBy properties of an entity.
So I added updating those to the FakeUpdate function.
Please note, that already in the previous commit there were tests failing:
FakeXrmEasy.Tests.FakeContextTests.LinqTests.EqualityWithDifferentDataTypesTests.When_executing_a_linq_query_with_equals_between_2_activityparties_result_is_returned
=> Assert.True() Failure
PS: Do you think you could publish an updated version in Nuget? I don't want to use local builds for all projects.
Kind Regards,
DigitalFlow
> Setting modified on and modified by on FakeUpdate now, too

- FakeXrmEasy.Tests/FakeContextTests/FakeContextMockTests.cs
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
- FakeXrmEasy.Tests/PluginsForTesting/CustomMockPlugin.cs
- FakeXrmEasy/XrmFakedContext.Plugins.cs
- FakeXrmEasy/XrmFakedContext.cs
I recently had the need to test plugins with some very special requests, that were not implemented in FakeXRMEasy.
Therefore I wanted to add means for easily passing in mocks for those requests.
With the additions in this pull request you can add delegates to a dictionary of the XrmFakedContext, which will be executed if the request, that they are defined for, is sent to the context.
Kind Regards
> Added possibility for mocking various request types

- FakeXrmEasy.Tests/FakeContextTests/RetrieveMultiple/QueryLinkEntityTests.cs
- FakeXrmEasy/FakeMessageExecutors/AssociateRequestExecutor.cs
- FakeXrmEasy/FakeMessageExecutors/DisassociateRequestExecutor.cs
- FakeXrmEasy/XrmFakedContext.Crud.cs
as I suspected yesterday, the intersect entity schema name was not used as it should have been.
I fixed that and changed the test request to look exactly like the MS examples, works as expected now.
> Fixed mixup of intersect entity schema name and logical name

- FakeXrmEasy.Shared/FakeMessageExecutors/AssociateRequestExecutor.cs
- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/QueryLinkEntityTests.cs
Changes in short:
- Natural joins are supported, however processed identical to inner joins
- Throw pull request exception if join type is not supported.
Do you think you could release a new NuGet package soon?
Current package does not include XrmFakedRelationship somehow.
Kind Regards,
Florian
> Added fix for natural joins 

- FakeXrmEasy.Shared/FakeMessageExecutors/UpdateRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestUpdate.cs
Hey Jordi,
Added a new Fake Executor for UpdateRequests, since OrganizationServiceContext uses this for updating entities.
Kind Regards,
Florian
> Added support for updating entities using organization context

- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestCreate.cs
I found a case where you add an entity to the context, but querying using Linq fails.
When specifying a proxy types assembly, the tests pass, but I think if the entities are present in the context, it should also work without proxy types assembly.
I would like to add a fix, what do you think?
Kind Regards,
Florian
> Added test that reveals possible bug while querying for entities

- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestRetrieve.cs
Hey Jordi,
as I found out, the service can return, that it does not know an entity, when in fact it is known by the proxy types assembly, but no record exists yet.
Therefore I added a fix, which looks in the proxy types assembly, too.
If no record is found, we don't return null, but throw a FaultException of type OrganizationServiceFault, that states, that the record with this ID was not found, because this is what the CRM does, too.
Kind Regards,
Florian
> Added fix for service retrieve not knowing entities, that it should know

- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestCreate.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestCreateQuery.cs
Hey Jordi,
with the changes from this commit, creating records and already passing in an entity id works.
Kind Regards,
Florian
> Allowing to pass in IDs on service create

- FakeXrmEasy.Shared/FakeMessageExecutors/CreateRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/DeleteRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestCreate.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestDelete.cs
Hey Jordi,
I implemented the create and delete requests, so that the organization context can now be used pretty universally.
This resolves #32.
Kind Regards,
Florian
> Added executors for create and delete requests

- FakeXrmEasy.Shared/XrmFakedContext.cs
I had an issue where my plugin used a RetrieveAttributeRequest.
There is a FakeMessageExecutor for RetrieveAttributeRequest, which throws a PullRequestException when executing.
I changed the order, in which FakeExecute searches for the implementation to first look for Execution Mocks, to give users the ability to override default behaviours.
In addition to that: I think we should not make the execution mocks obsolete, since adding an execution mock with a lambda expression is much more convenient than the FakeMessageExecutor.
Kind Regards,
Florian
> Changed FakeExecute: Prefer execution mocks over fake message executors

- build.fsx
the current release hides the ExecuteTransactionExecutor, since the build script passes the fake_xrm_easy_2015 constant instead of the 2016 one in the 2016 target.
With this fix, the ExecuteTransactionExecutor is compiled in the 2016 package.
Kind Regards,
Florian
> Fixed passing of 2015 constant to build target for crm 2016

- build.fsx
Hi Jordi,
as we found out, the assemblies contained in the NuGet packages don't match the package version, i.e. FakeXrmEasy 1.10.0 contains assemblies with version 1.9.1.
There is a build target called "AssemblyInfo", which is responsible for this and which searched for AssemblyInfos in the wrong path.
I changed it to search in the project root dir, should work now.
Kind Regards,
Florian
> Changed AssemblyInfo target to use correct path

- FakeXrmEasy.Shared/Extensions/XmlExtensionsForFetchXml.cs
By default, double.TryParse and friends uses the current thread culture.
When using a thread culture that has a decimal separator other than '.', money/doubles in fetchXml is parsed incorrectly. French, Italian, Swedish, Norwegian and others all use ',' as a decimal separator.
I think the correct way to handle the fetchXml is to insist on invariant culture for all numbers.
This fix makes all tests pass again on a norwegian system.
> Specify invariant culture for float/double/decimal values in fetchXml

- FakeXrmEasy.Shared/FakeMessageExecutors/AssignRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/AssociateRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/CloseQuoteRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/CreateRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/DeleteRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/DisassociateRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteMultipleRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteTransactionExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/IFakeMessageExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/InsertOptionValueRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/PublishXmlRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveAttributeRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveMultipleRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/ReviseQuoteRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/SetStateRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/UpdateRequestExecutor.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/WhoAmIRequestExecutor.cs
- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/CloseQuoteRequestTests/CloseQuoteRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextMockTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/ReviseQuoteRequestTests/ReviseQuoteRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
I added FakeMessageExecutors for CloseQuoteRequest and ReviseQuoteRequests.
I also found that it might be an advantage if all FakeMessageExecutors were discovered automatically on initialization, so that we don't forget to add new executors.
We should not get issues with version dependent executors like the ExecuteTransactionRequestExecutor, as it is not even available in older assemblies as far as I can tell.
I hope you like it. If you don't want the changes besides the new executors, just give me a note and I will exclude everything else.
Kind Regards,
Florian
> Added fake message executors, executors are discovered automatically

- FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteMultipleRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/ExecuteMultipleRequestTests/ExecuteMultipleRequestTests.cs
ExecuteMultipleRequest should return the OrganizationResponse.
> Pass the OrganizationResponse back when doing an ExecuteMultipleRequest

- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestCreate.cs
PrimaryKey attribute should be populated if it doesn't exist regardless of whether the entity is early bound or not or whether a ProxyTypes assembly is registered or not.
> PrimaryKey attribute should be populated if it doesn't exist

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
I have a custom Entity generator, I'm not using crmsvcutil. This is to provide custom functionality in my entities which crmsvcutil will not provide, among other things I don't return EntityReferences I return full populated Entities, since in 99% of cases (for me anyway) I want the full Entity, and not just a reference, returning the full Entity saves a lot of repetitive code to fetch the Entity from CRM. The same goes for related entity data.
My Entities obviously inherit from Xrm.Sdk.Entity and have the same basic structure as the crmsvcutil Entities, otherwise nothing would work with FakeXrmEasy! The main difference are the types of the Properties, they are all still decorated with the same AttributeLogicalNameAttribute.
However, in the case of the FakeXrm Query handler, obviously …
> Fix for #147

- FakeXrmEasy.2013/FakeXrmEasy.2013.csproj
- FakeXrmEasy.2013/packages.config
- FakeXrmEasy.2015/FakeXrmEasy.2015.csproj
- FakeXrmEasy.2015/packages.config
- FakeXrmEasy.2016/FakeXrmEasy.2016.csproj
- FakeXrmEasy.2016/packages.config
- FakeXrmEasy.365/FakeXrmEasy.365.csproj
- FakeXrmEasy.365/packages.config
- FakeXrmEasy.Tests.2013/FakeXrmEasy.Tests.2013.csproj
- FakeXrmEasy.Tests.2013/packages.config
- FakeXrmEasy.Tests.2015/FakeXrmEasy.Tests.2015.csproj
- FakeXrmEasy.Tests.2015/packages.config
- FakeXrmEasy.Tests.2016/FakeXrmEasy.Tests.2016.csproj
- FakeXrmEasy.Tests.2016/packages.config
- FakeXrmEasy.Tests.365/FakeXrmEasy.Tests.365.csproj
- FakeXrmEasy.Tests.365/packages.config
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
- FakeXrmEasy.Tests/packages.config
- FakeXrmEasy/FakeXrmEasy.csproj
- FakeXrmEasy/packages.config
I needed to update to 3.2 for other reasons - there are no problems with FakeXrmEasy, all tests passing. Makes sense to be on the latest release...
> Update to FakeItEasy 3.2

- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/TestGenericMessageExecutors.cs
This functionality allows for the addition of generic message handlers to allow for the mocking of things such as Actions which don't have a type associated with them.
> Add a generic handling for messages 

- FakeXrmEasy.Shared/XrmFakedContext.Aggregations.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/AggregateTests.cs
CRM still returns an aliased field even if it's empty for FetchXML request (without grouping).
For example:
```xml
<fetch version="1.0" output-format="xml-platform" mapping="logical" aggregate="true" >
<entity name="invoicedetail" >
<attribute name="extendedamount" alias="extendedamount_sum" aggregate="sum" />
<filter type="and" >
<condition attribute="productid" operator="eq" value="00000000-0000-0000-0000-000000000002" />
<condition attribute="invoiceid" operator="eq" value="cb8d1a91-9160-4702-a4bd-e5eff56f0bd7" />
</filter>
</entity>
</fetch>
```
Returns:
```xml
<resultset morerecords="0" >
<result>
<extendedamount_sum/>
</result>
</resultset>
```
> fix: FetchXml request with aggregation should still return an alias

- FakeXrmEasy.Shared/XrmFakedTracingService.cs
In context of #121 we should simply write the trace messages to the default output. This is then usually also collected by the unit test runners.
I am aware of the `DumpTrace` method, however I want to avoid adding boilerplate code to the unit tests, to see the trace messages which were produced.
Maybe it would make sense to prepend "Plugin: " before the trace output to have a visible differentiator for output coming from the plugin vs. output of the test itself
> The trace output should also be sent to the default output

- FakeXrmEasy.Shared/Extensions/XmlExtensionsForFetchXml.cs
Please include this change to handle conditions like below:
<condition attribute='fullname' value='%Dummy%' operator='like'/>
> Added support for like operator with % sign at both ends. e.g. %Dummy%

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
- FakeXrmEasy.Tests.Shared/Issues/TestCRMHandlingOfNullsAndMissingFields.cs
This fixes another problem with null handling and makes the handling more in line with the way dynamics handles it. The particular case that I ran into this was in a linked entity.
Current Functionality: Null fields are returned in the entity
CRM Functionality: Null fields are not returned in the entity
> Fixed an issue with more null handling

- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
I couldn't find a smart way to make GetFakedPluginContext call GetFakedExecutionContext and just add the two additional methods (ParentContext and Stage) so it's now a simple copy&paste of the existing code sans the 2 mentioned methods.
> Add support for ServiceProvider.GetService(typeof(IExecutionContext))

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/QueryLookupTests/QueryLookupTests.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
When querying CRM with a condition on a lookup property this is normally done using a `GUID`.
However, there is a construct where you append "name" as a suffix to the attribute name making the comparison not work on the `Id` property but the `Name` property of the `EntityReference`.
This PR adds support for this construct to FakeXrmEasy
> Add query support to filter on entityreference name property

- FakeXrmEasy.Shared/Services/EntityInitializer/DefaultEntityInitializerService.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestRetrieve.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/LinqTests/FakeContextTestLinqQueries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/TranslateQueryExpressionTests/FakeContextTestTranslateQueryExpression.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/TestDefaultEntityInitializer.cs
Sets the default owner of created entities to the current user if none is specified (which is the default for CRM)
> Set default owner on entity create

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/TranslateQueryExpressionTests/OrderByTests.cs
Fixes Orders in Query Expressions not working if the ordering field is not in the column set.
Current functionality:
Orders in Query Expressions don't actually order if the column isn't in the column set.
Patched functionality:
Orders in Query Expressions still sort even if the column is not in the column set.
> Fixes Orders in QueryExpression not working if column isn't in column set

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
> AliasedValues keep the original entity logical name, not the alias in the query

- FakeXrmEasy.Shared/XrmFakedContext.CodeActivities.cs
- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/Tracing/XrmFakeTracingExample.cs
It was not possible to retrieve a TracingService without calling Execute before. I've changed the implementation, so that this is now possible.
> TracingService could now be retrieved without executing a plugin before

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
> GreaterThen/GreaterEquals now throws the same exception as the real CRM server

- FakeXrmEasy.Shared/FakeMessageExecutors/ExecuteFetchRequestExecutor.cs
- FakeXrmEasy.Shared/XrmFakedContext.Pipeline.cs
- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/ExecuteFetchRequestTests/ExecuteFetchRequestTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/QueryLinkEntityTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/TranslateQueryExpressionTests/FakeContextTestTranslateQueryExpression.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
- FakeXrmEasy.Tests.Shared/Issues/Issue165.cs
- FakeXrmEasy.Tests.Shared/Issues/Issue191.cs
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
Added more CRM behaviour
- Only valid EntityAlias allowed at a LinkEntity in a QueryExression
- Naming of linked attributes is now incremental instead of overwritting other attributes
Should fix #165
> Make multiple unaliased joins work more like CRM

- FakeXrmEasy.Shared/Extensions/EntityMetadataExtensions.cs
- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveEntityRequestExecutor.cs
In my case used to be able to set ``PrimaryNameAttribute`` on the ``EntityMetadata``.
Sample:
```
private static EntityMetadata InitializeEntityMetadata(string logicalname, string primaryattribute = "name")
{
var meta = new EntityMetadata()
{
LogicalName = logicalname
};
meta.SetSealedPropertyValue("PrimaryNameAttribute", primaryattribute);
return meta;
}
```
> Adding SetSealedPropertyValue extension for EntityMetadata

- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
Otherwise both will be Guid.Empty even when set in faked plugin context.
> Set BusinessUnitId and CorellationId

- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeXrmEasy.Tests.Shared.projitems
The executor for NavigateToNextEntityOrganizationRequestExecutor was catching every generic OrganizationRequest which was in turn nullifying the generic message executor. This resolves that by checking if the message executor should be handling the message.
> Fix Generic Message Executor

- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
Something I noticed while developing is this property not being copied.
Required when deserializing the IExecutionContext (or RemoteExecutionContext) to json using DataContactJsonSerializer. Serializer does not allow DateTime.MinValue.
> Copy the OperationCreatedOn property to the newly created IExecutionContext

- FakeXrmEasy.Shared/Extensions/EntityMetadataExtensions.cs
- FakeXrmEasy.Tests.Shared/Extensions/EntityMetadataExtensionsTests.cs
If currentAttributes is null it will be set to an empty array before attempting to add an item to the list
> Added a quality of life enhancement to EntityMetadata.SetAttribute

- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestCreate.cs
In a real Dynamics CRM instance Create method of OrganizationService doesn't change entity object passed as a parameter (e.g. does not populate id field). I've moved the moment of cloning entity before applying default processing (like populating id, statecode, createdon fields) to emulate original behavior of the organization service.
> Fix for calling multiple Creates on a single object

- FakeXrmEasy.Shared/XrmFakedContext.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/RetrieveMultipleTests.cs
I noticed that FakeXrmEasy wasn't returning the Total Record Count when we passed in PageInfo with ReturnTotalRecordCount set to true. I wasn't able to complete a unit test and saw that this functionality was missing from FXE.
> PageInfo.ReturnTotalRecordCount on RetrieveMultiple

- FakeXrmEasy.Shared/XrmRealContext.cs
I modified a name of a variable in XrmRealContext constructor and changed GetOrgService method to accept ConnectionStringName as a pure connection string in case of missing it in configuration.
> #311 Added logic to use a pure connection string

- FakeXrmEasy.Shared/IXrmFakedContext.cs
- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestPlugins.cs
- FakeXrmEasy/Properties/AssemblyInfo.cs
- Removed unused parameters and deprecated some old ExecutePluginWith* methods.
- Removed the generic type on methods that accept a plugin instance since the type wasn't used
- Copied some documentation from IXrmContext to XrmFakedContext because intellisense works based on the type
> Polishing IXrmContext

- FakeXrmEasy.Shared/XrmFakedContext.Aggregations.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/AggregateTests.cs
Hi @jordimontana82,
I fixed the aggregate FetchXml queries to behave in the same way the CRM does, which is ignoring null values. The current implementation defaulted null values to 0 instead of ignoring them and was producing wrong values for the aggregates. I didn't change the sum aggregate because it is in a working state, but maybe i should have refactored that too so the methods would be similar.
Best regards, 
@BetimBeja 
Closes #355
> Fix for avg, min and max Aggregate FetchXml with null values 

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestUpdate.cs
Hello Jordi,
when attributes are set to null on update they should be removed from the context entity, as Roger mentioned in #388 .
Fixes #388.
Best regards,
Betim.
> Remove attribute from context entity when updating with null values.

- FakeXrmEasy.Shared/FakeXrmEasy.Shared.projitems
- FakeXrmEasy.Shared/Metadata/MetadataGenerator.cs
- FakeXrmEasy.Shared/XrmFakedContext.Metadata.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestMetadata.cs
this PR implements the functionality requested in issue #247.
One thing it is missing is mapping the Primary Id Attribute to UniqueIdentifierAttributeMetadata. Actually it produces EntityReference, since it gets mapped from a Nullable<Guid> type.
I believe that with this implementation we can start to use EntityMetadata in our algorithms for both EarlyBound and LateBound entities and probably we can even mix them without too much problems.
I used some code from @eNeRGy164 implementation but I don't know how to give him credit other than mentioning him 😄 
Best regards,
Betim.
> Added ability to generate metadata from EarlyBound entities

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/QueryLinkEntityTests.cs
Hello @jordimontana82,
as mentioned in issue #389 there was a problem that LinkEntity worked only on Guid or EntityReference. I changed KeySelector extension method to make the joins work on all entity types.
Fixes #389 
Best regards,
Betim.
> LinkEntities can be joined on all attribute types.

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveMultipleRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/QueryByAttribute/QueryByAttributeTests.cs
There is a bug in the translation from QueryByAttribute to QueryExpression because QueryByAttribute.Orders is being ignored, as discussed in issue #375.
Unit test provided by @AngelRodriguez8008.
This PR fixes #375.
> Orders are copied in the translation from QueryByAttribute to QueryExpression

- FakeXrmEasy.Shared/XrmFakedContext.Aggregations.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/AggregateTests.cs
Hello @jordimontana82,
as mentioned on #383 there was a bug when grouping on EntityReference attributes. The problem was that EntityReference was being casted as IComparable and it resulted in null values. I admit it was a little tricky to replicate the CRM behavior on this one.
Fixes #383.
Best regards,
Betim.
> Fix for Grouping on EntityReference attributes

- FakeXrmEasy.Shared/FakeMessageExecutors/AddToQueueRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/AddToQueueRequestTests/AddToQueueRequestTests.cs
I extended the AddToQueueRequestExecutor to behave more like CRM actually does.
Is there a possibility to overwrite the default executor by my custom executor while this PR is pending?
Previously the ExecutionMocks and FakeMessageExecutors added to a XrmFakedContext were prioritized higher than the default implementations, but this does not seem to happen anymore.
Kind Regards,
Florian
> Extended AddToQueueRequestExecutor

- FakeXrmEasy.Shared/Extensions/EntityExtensions.cs
- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestRetrieve.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestUpdate.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/RetrieveMultipleTests.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveRequestTests/RetrieveRequestTests.cs
As discussed in #366 to have the `Name` property of `EntityReference` populated, we must use `PrimaryNameAttribute` from `EntityMetadata` when the data is available in the context.
> EntityReference Name is populated when metadata is provided

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveRequestExecutor.cs
- FakeXrmEasy.Shared/XrmFakedContext.Crud.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestRetrieve.cs
Hello Jordi,
I believe that Centralizing the retrieve logic to one function, can avoid future problems with maintainability.  I also changed some tests because they were not implemented as stated :) 
Best regards,
Betim.
> IOrganizationService.Retrieve uses RetrieveRequestExecutor.

- FakeXrmEasy.Shared/XrmFakedContext.Queries.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveMultiple/RetrieveMultipleTests.cs
as mentioned in issue #403 the latests CRM online allows '.' in the entity alias.
I fixed it with this PR even though the error message when there are disallowed characters does not specify '.' as an allowed character.
Best regards,
Betim.
> EntityAlias is allowed to contain '.' character

- FakeXrmEasy.Shared/XrmFakedContext.Metadata.cs
I had copied some entitymetadata (over 300 entities) from a development system and initialized it using the InitializeMetadata method, but calling GetEntityMetadataByName was taking several minutes to complete. This change means they are returned within ms
>  Performance improvement for getting entitymetadata by name

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveRequestExecutor.cs
- FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextTestRetrieve.cs
Modified the exception thrown when retrieve does not find a record the FaultException has the same ErrorCode as the CRM Platform
> #424: Set ErrorCode

- FakeXrmEasy.Shared/FakeMessageExecutors/RetrieveEntityRequestExecutor.cs
I stumbled upon this Error today while using FakeXrmEasy to unit test a plugin. Took me some time to figure out where exactly the error came from and what it meant. 
This is just an idea for what to return, it'd just be good for the receiver of the error to need less time to figure out what went wrong.
> Return a clearer ErrorMessage for Invalid EntityFilter values

- FakeXrmEasy.2011.nuspec
- FakeXrmEasy.2013.nuspec
- FakeXrmEasy.2013/FakeXrmEasy.2013.csproj
- FakeXrmEasy.2013/packages.config
- FakeXrmEasy.2015.nuspec
- FakeXrmEasy.2015/FakeXrmEasy.2015.csproj
- FakeXrmEasy.2015/packages.config
- FakeXrmEasy.2016.nuspec
- FakeXrmEasy.2016/FakeXrmEasy.2016.csproj
- FakeXrmEasy.2016/packages.config
- FakeXrmEasy.365.nuspec
- FakeXrmEasy.365/FakeXrmEasy.365.csproj
- FakeXrmEasy.365/packages.config
- FakeXrmEasy.9.nuspec
- FakeXrmEasy.9/FakeXrmEasy.9.csproj
- FakeXrmEasy.9/packages.config
- FakeXrmEasy.Tests.2013/FakeXrmEasy.Tests.2013.csproj
- FakeXrmEasy.Tests.2013/packages.config
- FakeXrmEasy.Tests.2015/FakeXrmEasy.Tests.2015.csproj
- FakeXrmEasy.Tests.2015/packages.config
- FakeXrmEasy.Tests.2016/FakeXrmEasy.Tests.2016.csproj
- FakeXrmEasy.Tests.2016/packages.config
- FakeXrmEasy.Tests.365/FakeXrmEasy.Tests.365.csproj
- FakeXrmEasy.Tests.365/packages.config
- FakeXrmEasy.Tests.9/FakeXrmEasy.Tests.9.csproj
- FakeXrmEasy.Tests.9/packages.config
- FakeXrmEasy.Tests/FakeXrmEasy.Tests.csproj
- FakeXrmEasy.Tests/packages.config
- FakeXrmEasy/FakeXrmEasy.csproj
- FakeXrmEasy/packages.config
Rationale:
- FakeXrmEasy lib users might want to use more recent FakeItEasy version. 3.2.0 version is two and a half years old.
- Some projects want to migrate from spkl.fakes which references FakeItEasy >= 4.1.1. So it isn't possible to use both spkl.fakes and FakeXrmEasy in one test project.
Previous FakeItEasy versions changed how action exceptions are handled. They were wrapped in custom UserCallbackException. They actually reverted it back in version 5.3.0 (https://github.com/FakeItEasy/FakeItEasy/issues/1640).
So with zero code changed all tests are passed.
> Upgraded FakeItEasy to 6.0.0

- FakeXrmEasy.Shared/XrmFakedContext.Plugins.cs
The OwningExtension field is not being carried over from passed in FakedPluginExecutionContext.  Added to list.
> Add the OwningExtension to list of initializing fields.
